### ISSUE TITLE
Disable GitHub issues

### ISSUE THREAD

**Issue by wetneb** [JeanFred/inteGraality#1]
If issues are to be reported on Phabricator, perhaps should GitHub issues be disabled?

Note that the link provided to report issues, https://phabricator.wikimedia.org/tag/tool-integraality/, is not extremely user-friendly, as there is no button there to create a new issue… One needs to remember the project name, go to Phabricator's main page, create a new issue, and manually add the project to the form there…

**Comment by JeanFred** [comment]
That’s a good point − I added a direct link to Phabricator task creation form. Does that look good to you?

(Sorry for the lag, only seeing this report now ^_^")
