### ISSUE TITLE
no-group stats are offset by one column

### ISSUE THREAD

**Issue by 99of9** [JeanFred/inteGraality#16]
For example, see here: https://www.wikidata.org/wiki/Wikidata:WikiProject_Australia/Reports/Newspapers . I have also observed this on other dashboards. The issue seems to have started in late May of this year: https://www.wikidata.org/w/index.php?title=Wikidata%3AWikiProject_Australia%2FReports%2FNewspapers&diff=1904184235&oldid=1900926024

Thanks in advance!

**Comment by JeanFred** [comment]
Thanks for the report, and for isolating when it started! This helps me identifying 7b095a8a as the culprit. Thanks also for the example − I could confirm that the fix worked via https://www.wikidata.org/w/index.php?title=Wikidata%3AWikiProject_Australia%2FReports%2FNewspapers&diff=1982415843&oldid=1981181103

**Comment by 99of9** [comment]
Cheers!
